import type { AchievementDefinition } from './achievements';

export const ACHIEVEMENTS: AchievementDefinition[] = [
  {
    id: 'first_snowflake',
    name: 'First Snowflake',
    description: 'You logged your very first watched Christmas movie.',
    hint: 'Watch 1 movie.',
    icon: '❄️',
    check: (s) => s.totalWatched >= 1,
  },
  {
    id: 'snowball_starter',
    name: 'Snowball Starter',
    description: 'You have started to build your festive watchlist.',
    hint: 'Watch 5 movies.',
    icon: '☃️',
    check: (s) => s.totalWatched >= 5,
  },
  {
    id: 'blizzard_binger',
    name: 'Blizzard Binger',
    description: 'You powered through a flurry of festive films.',
    hint: 'Watch 20 movies.',
    icon: '🌨️',
    check: (s) => s.totalWatched >= 20,
  },
  {
    id: 'polar_explorer',
    name: 'Polar Explorer',
    description: 'You have ventured deep into festive territory.',
    hint: 'Watch 35 movies.',
    icon: '🧭',
    check: (s) => s.totalWatched >= 35,
  },
  {
    id: 'christmas_marathoner',
    name: 'Christmas Marathoner',
    description: 'You turned Christmas movies into a marathon event.',
    hint: 'Watch 50 movies.',
    icon: '🏅',
    check: (s) => s.totalWatched >= 50,
  },
  {
    id: 'north_pole_resident',
    name: 'North Pole Resident',
    description: 'Christmas movies are basically your habitat now.',
    hint: 'Watch 75 movies.',
    icon: '🏔️',
    check: (s) => s.totalWatched >= 75,
  },
  {
    id: 'twelve_days',
    name: '12 Days of Christmas',
    description: 'You kept the festive streak going for 12 days.',
    hint: 'Watch a movie daily for 12 days.',
    icon: '🎄',
    check: (s) => s.hasTwelveDayStreak,
  },
  {
    id: 'comfort_rewatch',
    name: 'Comfort Rewatch',
    description: 'Some Christmas movies never get old.',
    hint: 'Rewatch the same movie 3 times.',
    icon: '🔁',
    check: (s) => s.maxRewatchCount >= 3,
  },
  {
    id: 'the_grinch',
    name: 'The Grinch',
    description: 'Not every movie can be a Christmas miracle.',
    hint: 'Give a movie 1★.',
    icon: '😈',
    check: (s) => s.lowRatingAny,
  },
  {
    id: 'santas_favourite',
    name: "Santa's Favourite",
    description: 'You found a film worthy of Santa himself.',
    hint: 'Give a movie a perfect 10★.',
    icon: '🎅',
    check: (s) => s.highRatingAny,
  },
  {
    id: 'holiday_optimist',
    name: 'Holiday Optimist',
    description: 'You see the best in festive films.',
    hint: 'Give 10 movies a rating of 8★ or higher.',
    icon: '🌟',
    check: (s) => s.highRatingCount >= 10,
  },
  {
    id: 'coal_giver',
    name: 'Coal Giver',
    description: 'Some movies really missed the mark.',
    hint: 'Give 5 movies 2★ or lower.',
    icon: '🪨',
    check: (s) => s.lowRatingCount >= 5,
  },
  {
    id: 'the_critic',
    name: 'The Critic',
    description: 'You have opinions on a lot of movies.',
    hint: 'Rate 20 movies.',
    icon: '📝',
    check: (s) => s.totalRated >= 20,
  },
  {
    id: 'nice_list',
    name: 'Nice List',
    description: 'You are generous with your festive ratings.',
    hint: 'Keep your average rating above 5★.',
    icon: '✅',
    check: (s) => s.averageRating > 5,
  },
  {
    id: 'classic_connoisseur',
    name: 'Classic Connoisseur',
    description: 'You appreciate the classics before Y2K.',
    hint: 'Watch 5 movies released before 2000.',
    icon: '📼',
    check: (s) => s.classicWatched >= 5,
  },
  {
    id: 'genre_juggler',
    name: 'Genre Juggler',
    description: 'You sampled a bit of everything festive.',
    hint: 'Watch movies from 5 different genres.',
    icon: '🎭',
    check: (s) => s.genreVariety >= 5,
  },
  {
    id: 'decades_of_cheer',
    name: 'Decades of Cheer',
    description: 'You watched Christmas through the ages.',
    hint: 'Watch movies from 4 different decades.',
    icon: '📆',
    check: (s) => s.decadeVariety >= 4,
  },
  {
    id: 'animated_joy',
    name: 'Animated Joy',
    description: 'You love animated festive adventures.',
    hint: 'Watch 5 animated Christmas movies.',
    icon: '🧸',
    check: (s) => s.animatedCount >= 5,
  },
  {
    id: 'romcom_reindeer',
    name: 'Rom-Com Reindeer',
    description: 'You love a festive rom-com.',
    hint: 'Watch 5 Christmas romance movies.',
    icon: '💘',
    check: (s) => s.romanceCount >= 5,
  },
  {
    id: 'decorator',
    name: 'Decorator',
    description: 'You have a whole row of favourites lit up.',
    hint: 'Mark 10 movies as favourite.',
    icon: '🎀',
    check: (s) => s.favoriteCount >= 10,
  },
  {
    id: 'tree_full_of_lights',
    name: 'Tree Full of Lights',
    description: 'Your favourites list is glowing.',
    hint: 'Mark 20 movies as favourite.',
    icon: '✨',
    check: (s) => s.favoriteCount >= 20,
  },
  {
    id: 'background_cheer',
    name: 'Background Cheer',
    description: 'It’s on… even if you’re not really watching.',
    hint: 'Log 3 movies in one day.',
    icon: '📼',
    check: (s) => s.maxWatchedInDay >= 3,
  },
  {
    id: 'elf_mode',
    name: 'Elf Mode',
    description: 'You keep coming back like a dedicated Christmas elf.',
    hint: 'Use the app on 10 different days.',
    icon: '🧝‍♂️',
    check: (s) => s.usageDistinctDays >= 10,
  },
  {
    id: 'festive_weekender',
    name: 'Festive Weekender',
    description: 'A perfect weekend activity.',
    hint: 'Watch movies on both Saturday and Sunday.',
    icon: '📺',
    check: (s) => s.hasWeekendDouble,
  },
  {
    id: 'early_bird',
    name: 'Early Bird',
    description: 'You started Christmas early.',
    hint: 'Watch a Christmas movie before December.',
    icon: '🐦',
    check: (s) => s.hasPreDecemberWatch,
  },
  {
    id: 'tradition_keeper',
    name: 'Tradition Keeper',
    description: 'A ritual worth repeating.',
    hint: 'Watch the same movie in different years.',
    icon: '🕰️',
    check: (s) => s.hasYearlyRewatch,
  },
  {
    id: 'christmas_eve_watcher',
    name: 'Christmas Eve Watcher',
    description: 'You watched a movie on Christmas Eve.',
    hint: 'Watch a movie on Dec 24.',
    icon: '🕯️',
    check: (s) => s.hasChristmasEveWatch,
  },
  {
    id: 'new_years_cozy',
    name: "New Year's Cozy",
    description: 'You started the year with a cozy movie.',
    hint: 'Watch a movie on Jan 1.',
    icon: '🎆',
    check: (s) => s.hasNewYearsWatch,
  },
];
